text:
    char_set: "PE abcdefghijklmnopqrstuvwxyz'.?"

audio:
    n_mels: 80
    n_fft: 1024
    phn_dim: 70
    sample_rate: 16000
    frame_length_ms: 50
    frame_shift_ms: 12.5
    preemphasis: 0.97
    min_level_db: -100
    ref_level_db: 20
    power: 1
    griffin_lim_iters: 200
    order: 25
    alpha: 0.42

model:
    optimizer:
        type: "Adam"
        lr: 0.001
        grad_clip: 1.0
        weight_decay: 0.0
        adam_beta1: 0.9
        adam_beta2: 0.999

solver:
    use_gpu: True
    num_workers: 4
    batch_size: 16
    total_steps: 300000
    checkpoint_interval: 2000

preprocess:
    leave_out_spk_id: "p258 p277 p330 p315"
    data_split:
        train: 0.8
        eval: 0.1
        test: 0.1

path:
    align_result: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/VCTK_aligned_result/aligned_result"
    all_data_dir: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/VCTK-Corpus/for_align"
    train_meta_path: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/train_meta.txt"
    eval_meta_path: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/eval_meta.txt"
    test_meta_path: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/test_meta.txt"
    feat_dir: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/feat"
    phn_dict_path: "/home_local/hoa/Desktop/non-parallel-rhythm-flexible-VC/data/phn_map.txt"
